"""
model-service/app/scoring/prompt_evolver.py
Prompt 自我进化器——Designer/Reflector 的元认知层。

核心思路：
- Reflector 每 20 次反思后，PromptEvolver 用 LLM 审视最近的反思质量
- 如果 observation 越来越模板化（"代码整洁"这类废话），自动改写 prompt 加入约束
- 如果 hypothesis 命中率低于 30%，改写 hypothesis prompt 让它更谨慎
- 进化后的 prompt 存入 StyleMemory，下次反思自动使用

学术依据：
- SPADE（arXiv:2608.19197）：Designer 的自我校准是能力涌现的关键
- Reflexion（Shinn et al. 2023）：语言反馈比数值奖励更有效地驱动改进
- Constitutional AI（Bai et al. 2022）：用自然语言原则约束输出质量
"""
from __future__ import annotations

import json
import logging
import re
from typing import Dict, List, Optional

from ..judge_backend import JudgeCompletion, JudgeUnavailable, get_backend
from .style_memory import (
    REFLECTION_SYSTEM_PROMPT,
    HYPOTHESIZE_SYSTEM_PROMPT,
    StyleMemory,
)

logger = logging.getLogger("prompt_evolver")


# ---------------------------------------------------------------------------
# Meta-Prompt 模板
# ---------------------------------------------------------------------------

_META_REVIEW_SYSTEM = """\
You are a prompt quality auditor. Your job is to evaluate the quality of
reflection observations generated by an LLM and decide whether the system
prompt that produced them needs to evolve.

You evaluate on three axes:
1. SPECIFICITY: Does each observation cite concrete code patterns, or is it generic praise?
2. NOVELTY: Does each observation reveal something new, or restate previous understanding?
3. ACTIONABILITY: Could a challenge designer use this observation to create a better test?

Template-like observations are the enemy. Patterns like "代码整洁", "结构清晰",
"总体不错" without citing specific code are worthless — they don't help the Designer.
"""

_META_REVIEW_USER = """\
Below are the most recent reflection observations, oldest first:
--- OBSERVATIONS ---
{observations}
--------------------

And the hypotheses that preceded them:
--- HYPOTHESES ---
{hypotheses}
-------------------

Current understanding (synthesized from prior observations):
{understanding}

Evaluate:
1. What fraction of observations are template-like / generic (no specific code evidence)?
2. What fraction of hypotheses were confirmed by the subsequent observation?
3. Are there recurring blind spots the prompt should address?

Respond in JSON:
{{
  "quality_score": 0.0-1.0,
  "hypothesis_accuracy": 0.0-1.0,
  "template_ratio": 0.0-1.0,
  "evolve_reflection": true/false,
  "evolve_hypothesis": true/false,
  "new_reflection_constraints": "one sentence describing what the new reflection prompt should emphasize (or empty if no evolution needed)",
  "new_hypothesis_constraints": "one sentence describing what the new hypothesis prompt should emphasize (or empty if no evolution needed)",
  "reasoning": "brief explanation of your assessment"
}}
"""


# ---------------------------------------------------------------------------
# PromptEvolver
# ---------------------------------------------------------------------------

class PromptEvolver:
    """审查反思质量，自动进化 Designer/Reflector 的 system prompt。

    触发条件：每 ``evolve_every`` 次反思（默认 20）。
    进化逻辑：
    - quality_score < 0.5 或 template_ratio > 0.4 → 进化 reflection prompt
    - hypothesis_accuracy < 0.3 → 进化 hypothesis prompt
    进化后的 prompt 写入 StyleMemory，下次反思自动使用。
    """

    def __init__(self, temperature: float = 0.4, max_tokens: int = 1024):
        self.temperature = temperature
        self.max_tokens = max_tokens

    def should_check(self, memory: StyleMemory) -> bool:
        """是否到了触发审查的时机。"""
        if memory.reflection_count == 0:
            return False
        return memory.reflection_count % max(1, memory.evolve_every) == 0

    def check_and_evolve(self, memory: StyleMemory) -> StyleMemory:
        """审查最近的反思质量，必要时进化 prompt。

        Returns:
            更新后的 StyleMemory（evolved_* 字段可能被修改）
        """
        recent_obs = memory.observations[-10:]
        recent_hyps = memory.hypothesis_history[-10:]

        if not recent_obs:
            return memory

        # LLM 审查
        review = self._review(
            observations=recent_obs,
            hypotheses=recent_hyps,
            understanding=memory.current_understanding,
        )
        if review is None:
            return memory

        # 记录质量/准确率历史
        quality = float(review.get("quality_score", 0.5))
        accuracy = float(review.get("hypothesis_accuracy", 0.5))
        memory.reflection_quality_history.append(quality)
        memory.hypothesis_accuracy_history.append(accuracy)

        logger.info(
            "PromptEvolver review: team=%s quality=%.2f accuracy=%.2f template_ratio=%.2f",
            memory.team_id, quality, accuracy,
            float(review.get("template_ratio", 0)),
        )

        evolved_any = False

        # 进化 reflection prompt
        if review.get("evolve_reflection") and review.get("new_reflection_constraints"):
            current = memory.evolved_reflection_system or REFLECTION_SYSTEM_PROMPT
            new_prompt = self._evolve_prompt(
                current_prompt=current,
                constraint=review["new_reflection_constraints"],
                prompt_type="reflection",
            )
            if new_prompt and new_prompt != current:
                memory.evolved_reflection_system = new_prompt
                memory.evolution_count += 1
                evolved_any = True
                logger.info(
                    "Reflection prompt evolved for team %s (evolution #%d)",
                    memory.team_id, memory.evolution_count,
                )

        # 进化 hypothesis prompt
        if review.get("evolve_hypothesis") and review.get("new_hypothesis_constraints"):
            current = memory.evolved_hypothesis_system or HYPOTHESIZE_SYSTEM_PROMPT
            new_prompt = self._evolve_prompt(
                current_prompt=current,
                constraint=review["new_hypothesis_constraints"],
                prompt_type="hypothesis",
            )
            if new_prompt and new_prompt != current:
                memory.evolved_hypothesis_system = new_prompt
                memory.evolution_count += 1
                evolved_any = True
                logger.info(
                    "Hypothesis prompt evolved for team %s (evolution #%d)",
                    memory.team_id, memory.evolution_count,
                )

        if not evolved_any:
            logger.debug("No evolution needed for team %s", memory.team_id)

        return memory

    # ------------------------------------------------------------------
    # LLM 调用
    # ------------------------------------------------------------------

    def _review(
        self,
        observations: List[str],
        hypotheses: List[str],
        understanding: str,
    ) -> Optional[Dict]:
        """调用 LLM 审查反思质量。"""
        obs_text = "\n".join(f"{i+1}. {o}" for i, o in enumerate(observations))
        hyp_text = "\n".join(f"{i+1}. {h}" for i, h in enumerate(hypotheses)) if hypotheses else "(no hypotheses yet)"

        user = _META_REVIEW_USER.format(
            observations=obs_text,
            hypotheses=hyp_text,
            understanding=understanding.strip() or "(none yet)",
        )

        try:
            raw = self._call_llm(system=_META_REVIEW_SYSTEM, user=user)
        except JudgeUnavailable:
            logger.warning("PromptEvolver: LLM unavailable, skipping review")
            return None
        except Exception:
            logger.exception("PromptEvolver: review LLM call failed")
            return None

        return self._parse_json(raw)

    def _evolve_prompt(
        self,
        current_prompt: str,
        constraint: str,
        prompt_type: str,
    ) -> Optional[str]:
        """基于约束生成进化后的 prompt。"""
        system = (
            "You are a prompt engineer. You improve system prompts based on "
            "quality feedback. Keep the core role and output format intact. "
            "Add the requested constraint naturally into the existing prompt. "
            "Return ONLY the new system prompt text, no explanations."
        )
        user = (
            f"Current {prompt_type} system prompt:\n"
            f"---\n{current_prompt}\n---\n\n"
            f"Quality feedback: {constraint}\n\n"
            f"Rewrite the prompt to address this feedback. Keep the same role, "
            f"structure, and output format. Add the improvement as a clear "
            f"instruction within the prompt. Return only the new prompt text."
        )

        try:
            raw = self._call_llm(system=system, user=user, max_tokens=2048)
        except JudgeUnavailable:
            logger.warning("PromptEvolver: LLM unavailable for evolution")
            return None
        except Exception:
            logger.exception("PromptEvolver: evolution LLM call failed")
            return None

        cleaned = raw.strip()
        # 基本校验：进化后的 prompt 不能太短（防止 LLM 返回废话）
        if len(cleaned) < 50:
            logger.warning("PromptEvolver: evolved prompt too short, discarding")
            return None
        return cleaned

    def _call_llm(self, system: str, user: str, max_tokens: Optional[int] = None) -> str:
        backend = get_backend()
        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]
        completion: JudgeCompletion = backend.complete(
            messages,
            temperature=self.temperature,
            max_tokens=max_tokens or self.max_tokens,
        )
        return getattr(completion, "text", None) or ""

    @staticmethod
    def _parse_json(text: str) -> Optional[Dict]:
        """从 LLM 响应中提取 JSON。"""
        if not text:
            return None
        # 去掉 markdown 代码块
        cleaned = re.sub(r"```(?:json)?\s*", "", text)
        cleaned = re.sub(r"```\s*$", "", cleaned.strip())
        # 找第一段 {...}
        match = re.search(r"\{.*\}", cleaned, re.DOTALL)
        if not match:
            return None
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            return None
